version: '3.2'
services:
  db:
    container_name: projeqtor-postgresql
    image: "postgres:${POSTGRES_VERSION}"
    volumes:
      - db-data:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER:-projeqtor}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-projeqtor}
      - PG_DATA=${PG_DATA:-/data/postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_VERSION=${POSTGRES_VERSION:-latest}
  
  projeqtor:
    build:
      dockerfile: "./docker/.Dockerfile"
      context: .
    container_name: projeqtor
    extra_hosts:
      - "ldapapp:${LDAP_HOST}"
    ports:
        - "${PROJEQTOR_PORT:8080}:80"
        
  pgAdmin:
    container_name: "projeqtor-admin"
    image: "dpage/pgadmin4"
    ports:
      - "${PGADMIN__PORT}:${PGADMIN_LISTEN_PORT}"
    links: 
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT:-443}
      - PGADMIN_PORT=${PGADMIN_PORT:-6543}
volumes:
  db-data:
